version: '3.4'

services:
  fiap.portal:
    image: ${DOCKER_REGISTRY-}fiapportal
    ports:
        - "80:80"
    build:
      context: .
      dockerfile: FIAP.Portal/Dockerfile
    depends_on:
        - db
    container_name: web

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - 1433:1433
    environment:
        SA_PASSWORD: "@Fiap_123"
        ACCEPT_EULA: "Y"

  fiap.parceriaapi:
    image: ${DOCKER_REGISTRY-}fiapparceriaapi
    ports:
        - "5555:5555"
        - "5556:5556"
    build:
      context: .
      dockerfile: FIAP.ParceriaAPI/Dockerfile
    depends_on:
        - db
    container_name: api  

